name: CI Test Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
      - name: Run Django Testcases
        run: |
          python manage.py test Patients

        - name: Run Django Testcases
          run: |
            python manage.py test Patients
